---
title: "ESS Lab 9: Results and Disscussion Draft"
authors:
  - name: Avery Eastman
    affiliation: CSU
    roles: writing
    corresponding: true
  - name: Ava Zelenz
    affiliation: CSU
    roles: writing
    corresponding: false
    
format: html
execute:
  echo: true
---

## Method

We believe that the methods we have chosen for the analysis are strong. We’ve done many different types of tests to determine the ones that suit our data best, resulting in the following, 
The implementation of these methods has been done carefully and attentively. We have effortlessly made sure that our methods have been structured and implemented in the nest of our ability. The data proved to be difficult to work with, especially when determining which tests could be used in the best way. The first thing we began with was acquiring data from data.gov, from the metadata set called “Soil Responses to Inclusion of Corn, Soybean, and Cover Crops under Rainfed Conditions in the Northern Great Plains”. We utilized the datasets named SES_On_Station_Intergrative Measures_SMAF_Metadata and SES_On_Station_Soil_Properties_Near Surface_Metadata. These datasets were chosen due to the variables they entailed. Those being treatment description and designation, replication, soil depth, and many soil health indicating variables, like microbial elements, and most importantly, a soil quality index score. These variables allowed us to get a better understanding of how different treatments can affect the soil quality, which is our main goal. Once the data was loaded, we inspected its properties using glimpse(). We then merged datasets using merged_data and left_join. We merged the columns STUDY, LTEXP, TRT, LAND_USE, YEAR, REP, and DEPTH.
 
Through Exploratory Data Analysis, we were able to understand the data structure. This included identifying outliers, creating visualizations, and getting summary statistics. We were able to check types, dimensions, and missing values. We then identified data issues, like outliers, missing data, and inconsistencies, using vis_dat and vis_miss. There were two columns that showed a high percentage of missing values, so to combat this, we created another dataset and filtered out those two columns. After removing this, we then began to utilize summary statistics by using the codes summary(merged_data), and used library(skimr) to run skim(merged_data), allowing us to look at the histogram output column to view the general trend in skewness for each variable. After using data_clean and select(-VESS, -TOC), we began data visualization. Using our data_clean dataset, we created a numberic_data dataset and utilized select(where(is.numeric)) along with vis_cor(numerica_data). This separation of numeric data allowed us to see the visualization of the correlation matrices of the numeric data. We ran this to assess which variables were more strongly correlated to the soil quality index score, and made sure that those variables also correlated to each other. We selected a few to do correlation matrices on. These included WSA, UREASE, SMAFQI, BGLU, TFAME, PHOS, and BACSUM. Then, using the select function on these values, we used ggarrange(gghistogram) to create a visual representation of this correlation. After this representation of data, we used ggplot to create a geom_boxplot to create a boxplot of soil quality index by long-term experiment. This box plot showed us that the soil quality was highest with the treatment of Integrated Crop-Livestock Study, moderate with the Biofeedstock Removal Study, and average with Crop Rotation Study.  Next, we created a density plot of SMAFQI by management practice treatment type using goem_density(). This density plot showed us that the densest points of our data were related to the Integrated Crop-Livestock Study. The curves of the data peak are where the most concentrated data is, while the width of the curves represents the variance, with a thinner curve representing a lower variance. The last visualization test was the ggviolin. This plot, like a boxplot, visualizes the median, outliers, and percentiles of the dataset. What differs from the normal box plot with a violin plot is the outer curve around the box plot. This curve represents the density of the data distribution for each variable. The wider areas of the curve signify more data points, while the narrower areas signify fewer data points. 
After these visualizations, we switched to assessing normality with the Shapiro-Wilk Test. We used shapiro.test on the same seven variables as the correlation tests. These tests showed p-value tests all smaller than 1. Most of which were in the range of 0.0003 to 0.0008. This signifies that there is very strong evidence against the null hypothesis (i’m not sure if this bit is correct, i only have a picture with three of the shapiro test results). After these tests, we tried log transformations because the variables did not fit a normal distribution. This was done with ggarrange(gghistogram(log(data_clean$SMAFSQI) and gghistogram(log(data_clean$BGLU). 
We then tried a normality test on log-transformed BGLU and BACSUM. Because the log-transformed data looked normally distributed, we used the Pearson’s correlation test, using cor.test. Next, we performed the correlation test again but kept the raw data and instead specified method = ‘spearman’, as the Spearman test is better for non-parametric and non-linear data sets.  Then we ran the Spearman test on SMAFSQI with BGLU, and then tried it with BACSUM. 


## Results

We performed correlation tests between all the predictor variables, graphs assess the distribution to make sure the data correlates well. All the numerical values have a strong correlation with each other, meaning they can be used to predict each other. To fully analyze this BGLU, and BACSUM to predict the SMAFSQI. We did this by using a workflow, made a model, recipe, applied recipe to model, fit our data to the workflow to see how much of the variability in the SMAFSQI is attributed to BGLU and BACSUM. 
Our results from the Kruskal-wallis rank sum test, which was chosen because our data is not normally distributed, showed us whether there was a significant overall difference between our management practices. It showed a significant P-value, showing that soil quality and biological indicators differ significantly between different management practices. 
Our violin plots illustrate the differences in soil quality score across treatment types and land uses. There is a clear difference between the 2 crop rotation practices, spring wheat - Fallow & continuous cropping, with spring wheat - Fallow ranking the lowest overall. Across all 3 indicators (SMAFSQI, BGLU, BACSUM), grazed continuous cropping consistently supports higher soil health. Cover cropping and diverse rotation ranks perform better than simple or fallow-based rotations. This aligns well with ecological understanding that diversification and continuous living cover support soil function and microbial activity. 
From the metrics output of the final model, we can see an R-squared value of ~ 0.931, meaning that our model explains approximately 93.1% of the variation in soil quality scores. The plot shows that higher soil quality scores (yellow-green) cluster where both BGLU and BACSUM are high, and lower soil quality scores (purple-blue) are more common where both BGLU and BACSUM are low. The numerical values we chose have an overall strong positive correlation with each other, suggesting that higher BGLU and BACSUM values are associated with higher SMAFSQI scores, supporting their relevance as soil health indicators. The plot shows a moderate relationship between BGLU and BACSUM, and you can see higher soil quality scores cluster where both BGLU and BACSUM are high, and lower soil quality scores are more common where both BGLU and BACSUM are low. The upward-sloping blue regression line indicates a moderate-to-strong positive correlation between Beta-Glucosidase Activity and Bacteria-marker FAME


## Discussion

Our findings support the hypothesis: crop-livestock integration and the use of cover crops result in significantly higher soil quality index scores in rainfed Northern Great Plains systems. These practices stimulate microbial activity and enhance soil biological structure, offering a resilient path forward for sustainable dryland agriculture. Our results suggest that diversification and cover cropping support soil function and microbial activity. Like other research, our data and study confirm that biological pathways, like microbial stimulation from plant diversity, are likely to cause yield improvements. The major limitation of our study was the small sample size of the data we had to work with. There were many difficulties at the beginning of our study that led us to change the scope and the main idea of the study itself. Unfortunately, despite our efforts to work through these issues, some were too limiting for us to be productive in terms of our study and our methods. We would recommend shifting over from traditional practices to practices like cover cropping and diversified rotations that maintain or improve SQI for long-term sustainability. A main issue we had seen in other studies relating to this topic is the public perception of cover cropping and diverse rotations. Some main issues the public has with these methods are concerns about yield consistency and efficiency. This study is evidence that with the use of these two methods, the yield production is likely to increase as the soil quality and health have a significant improvement compared to soil that has not been treated with the two methods mentioned. 


